### ISSUE TITLE
Support for SVG?

### ISSUE THREAD

**Issue by DinoJay** [ooade/react-rough#116]
It does not like that SVG render is supported.

Best,
Jan

**Comment by ooade** [comment]
I don't quite get this @DinoJay ?

**Comment by nickmcmillan** [comment]
By default this library renders in canvas. @DinoJay might have been asking if it's possible to render in SVG.

Through reading the source code I discovered that it is, by passing in "svg" as the renderer prop, like so;
```
<ReactRough renderer="svg">
   ...
</ReactRough>
```

It might be worth including this in the readme.

**Comment by ooade** [comment]
Thanks! I'll add that to the READme @nickmcmillan 🙏
