### ISSUE TITLE
onRender prop is ignored (not implemented?)

### ISSUE THREAD

**Issue by paradoxxxzero** [ooade/react-rough#123]
It is shown here though: https://jsfiddle.net/ooade/f8cmbfwL/

Edit: seems to have been removed in 1.0.0

**Comment by ooade** [comment]
Do we still need to give users access to the `rc` object, since one of the main reasons of having this hook is to animate the canvas elements?

**Comment by paradoxxxzero** [comment]
No, #127 fix it for me

**Comment by ooade** [comment]
Will you like to be added as a collaborator? @paradoxxxzero @MiroslavPetrik

**Comment by paradoxxxzero** [comment]
I wouldn't mind
