### ISSUE TITLE
Release version 2

### ISSUE THREAD

**Issue by ooade** [ooade/react-rough#129]
We'll be releasing a new version because of the breaking changes; changing from static methods to actual functions and all.

What other things do we need to add before releasing this version?
I was thinking about the web worker thing as specified [here](https://github.com/ooade/react-rough/issues/99)

What else @paradoxxxzero ?

**Comment by paradoxxxzero** [comment]
This change https://github.com/ooade/react-rough/pull/121#issuecomment-461098001 I think.
And some documentaion :)

**Comment by Youngestdev** [comment]
Perhaps move to using hooks since 16.8.2 is out ?

https://gist.github.com/Youngestdev/cc5e487fc7f10b1f25957ab54990a922 - Here's a brief.

**Comment by ooade** [comment]
Looks good. You can send a draft PR when you're ready.

**Comment by Youngestdev** [comment]
Oh cool
