### ISSUE TITLE
Polygon in readme example not visible

### ISSUE THREAD

**Issue by Sventenhaaf** [ooade/react-rough#165]
Hey there,

thanks for your package. I just wanted to say that in the readme, the example code for multiple shapes says:
```
...
render(
	<ReactRough width={200} height={400}>
		<Circle points={[50, 50, 80]} fill="red" />
		<Polygon
			points={[[[690, 130], [790, 140], [750, 240], [690, 220]]]}
                         ...
```

Since the canvas is too narrow (width  is too small), the Polygon is not visible. I don't seem to have rights to create a PR but the fix is simple, just make the width 800:

```
...
render(
	<ReactRough width={800} height={400}>
		<Circle points={[50, 50, 80]} fill="red" />
		<Polygon
			points={[[[690, 130], [790, 140], [750, 240], [690, 220]]]}
                         ...
```

I hope this will help others in the future.

**Comment by ooade** [comment]
Oh, wow! You can create a PR. 

Thanks 🎉
