### ISSUE TITLE
Text Rendering

### ISSUE THREAD

**Issue by yunusemredilber** [ooade/react-rough#269]
Is there any way to render a text or another canvas element?

I found [this example](https://bl.ocks.org/aaizemberg/b403ba342cf0cd32d3e8a77174dcf8a0) that uses native rough.js.

**Comment by ooade** [comment]
They actually didn't render a text with rough. They used [Amatic SC](https://fonts.google.com/specimen/Amatic+SC?preview.text_type=custom) font.

And yeah, you can render as much canvas elements as possible.
