### ISSUE TITLE
Doesn't work with roughjs v4.3.1

### ISSUE THREAD

**Issue by hamza1220** [ooade/react-rough#270]
[This](https://codesandbox.io/s/react-simple-maps-rough-js-forked-q0slr?file=/src/index.js) sandbox works for roughjs v3.1.0 with react-rough v2.0.0-beta.12 but gives the following error when upgrading to roughjs v.4.3.1:

```
Could not find module in path: 'roughjs/dist/rough.umd' relative to '/node_modules/react-rough/dist/react-rough.es.js'
```

Upgrading react-rough to v.2.3.0 also does not fix the issue

**Comment by ooade** [comment]
Yeah. There's a breaking change from v3 to v4 from the rough package. 

And, we also moved to a declarative approach. Apologies for the inconveniences 🙏
