### ISSUE TITLE
Recreate React-Rough

### ISSUE THREAD

**Issue by ooade** [ooade/react-rough#95]
Now that Rough has been added to npm: https://github.com/pshihn/rough/issues/3, I think it'd be nice to use rough directly and recreate the entire codebase as we have some outdated stuff :sweat_smile:

**Comment by rbansalrahul6** [comment]
Hi, I found the library [https://github.com/pshihn/rough](url) really fantastic. I am also a beginner in react and open source. I would like to contribute for the issue. Please guide me.

**Comment by ooade** [comment]
@rbansalrahul6 Nice! I've recreated the codebase, so it should be fairly easy to move around :sweat_smile: You can start by creating the Circle components, Arc Components and so on.
The Rough Components should be able to work as an independent component as well a child component. 

I think that should do for now. 

Besides, I haven't updated the readme, yet

**Comment by ooade** [comment]
@melMass The render props has always been there. It works [here](https://github.com/ooade/react-rough/blob/master/examples/basic/index.js)

**Comment by ooade** [comment]
A new API is upon us! :smile:
